### ISSUE TITLE
Build on Google Player or somewhere else

### ISSUE THREAD

**Issue by marco-brandizi** [skadyrov/CSipSimple#10]
Hi, 

I've just discovered CSipSimple, the original project seems to be abandoned and this fork has nice features. Does it have a maintained .apk that is ready to install? Maybe in the Google Player?

Thanks in advance,
Marco

**Comment by skadyrov** [comment]
Hi Marco,

You should be able to install it if you have Android Studio or just using gradle. You don't need to configure anything to be able to install it. It is also published on GooglePlay: https://play.google.com/store/apps/details?id=ait.ac.at.hbs.miraculouslife.sip
In readme file you can see the summary of differences between this fork and the parent repository.

**Comment by marco-brandizi** [comment]
Cool! Thanks a lot!
