### ISSUE TITLE
How do you build the .so files?

### ISSUE THREAD

**Issue by velis74** [skadyrov/CSipSimple#14]
Hi,

I'm trying to make this app work (and it does), but I'd also like to build the library files myself. Would you be willing to share details on how you build the .so files from pjsip sources? I'd be glad to compensate you if you would.

**Comment by skadyrov** [comment]
Hi,

I did not build the native libraries by myself. I only needed to make some changes to the Android app, therefore I used already built .so files. You can get them from apk files from nightly builds: https://nightlies.csipsimple.com/trunk/

If you want to build them yourself, you can find the instructions here: https://code.google.com/archive/p/csipsimple/wikis/HowToBuild.wiki

**Comment by velis74** [comment]
Thank you very much for this information
